# services:
#   api-test:
#     build:
#       context: .
#       dockerfile: Dockerfile
#     container_name: api-test
#     command: sh -c "npx prisma migrate reset --force && npm test"
#     env_file:
#       - .env.test
#     depends_on:
#       postgres-test:
#         condition: service_healthy
#     volumes:
#       - .:/app
#       - /app/node_modules
#     networks:
#       - test_net

#   postgres-test:
#     image: postgres:15-alpine
#     container_name: postgres-test
#     environment:
#       POSTGRES_USER: postgres
#       POSTGRES_PASSWORD: postgres
#       POSTGRES_DB: microblog_test
#     ports:
#       - "5433:5432"
#     healthcheck:
#       test: ["CMD-SHELL", "pg_isready -U postgres"]
#       interval: 2s
#       timeout: 2s
#       retries: 15
#     networks:
#       - test_net

#   redis-test:
#     image: redis:7-alpine
#     container_name: redis-test
#     networks:
#       - test_net

# networks:
#   test_net:
#     driver: bridge

services:
  api-test:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api-test
    command: sh -c "npx prisma generate && npx prisma db push --force-reset && npm test"
    env_file:
      - .env.test
    depends_on:
      postgres-test:
        condition: service_healthy
      redis-test:
        condition: service_started
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - test_net

  postgres-test:
    image: postgres:15-alpine
    container_name: postgres-test
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: microblog_test
    # ❌ sin volúmenes: efímero
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 2s
      timeout: 2s
      retries: 15
    networks:
      - test_net

  redis-test:
    image: redis:7-alpine
    container_name: redis-test
    command: ["redis-server", "--save", "", "--appendonly", "no"] # efímero
    networks:
      - test_net

networks:
  test_net:
    driver: bridge
